### ISSUE TITLE
Compute_Clique_Top fails on Mac

### ISSUE THREAD

**Issue by osw2002** [nebneuron/clique-top#1]
Hello,

I was testing this code on a simulated/random correlation matrix, when I got the following error message:
```matlab
>>>A = rand(10,10);
>>>A = A*A';
>>> compute_clique_topology(A)
/bin/bash: /Users/xxx/Documents/MATLAB/clique-top/perseus/perseusMac: Permission denied
  MException with properties:

    identifier: 'MATLAB:FileIO:InvalidFid'
       message: 'Invalid file identifier. Use fopen to generate a valid file identifier.'
         cause: {0×1 cell}
         stack: [2×1 struct]

Invalid file identifier. Use fopen to generate a valid file identifier.
Failure to read Perseus output files. This error has likely occurred due to the Perseus process aborting due to memory limitations. It may be possible to circumvent this difficulty by reducing either the maximum Betti number or the maximum edge density computed. Please see the CliqueTop documentation for details.
Error using read_perseus_bettis (line 62)
Invalid file identifier. Use fopen to generate a valid file identifier.

Error in compute_clique_topology (line 262)
    bettiCurves = read_perseus_bettis(sprintf('%s_homology_betti.txt',...
```

Matlab version is 2018a Mac.

**Comment by vitskov** [comment]
Hello, 


Note that this package is currently un-maintained due to becoming obsolete. The reason why I consider Clique_Top obsolete  is it's use of the  Perseus package for persistent homology computations. Currently, Perseus  is not as efficient as Ripser or Eirene on large data. This opinion only applies to computations with clique complexes though. 

A better/faster/more efficient  way to accomplish the same thing is using the julia Eirene package. 
See https://github.com/Eetion/Eirene.jl
Note that one needs to use Julia (as opposed to matlab), but I consider this a bonus :-).

Best,
Vladimir
